# @format
apiVersion: v1
kind: ReplicaSet
metadata:
  name: firstreplicapod
  labels:
    appname: voatingapp

spec:
  replicas: 5
  selector:
    matchExpressions:
      - key: appname
        operator: In
        values:
          - voatingapp
          - voatingapp2
      - key: type
        operator: NotIn
        values:
          - backend
  template:
    metadata:
      labels:
        appname: voatingapp
    spec:
      containers:
        - name: firstcontainer
          image: coolgourav147/nginx-custom
